name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: wickedyoda
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build Photo-stream Docker image
run: |
       docker build . --tag ghcr.io/wickedyoda/photo-stream:latest
       docker run ghcr.io/wickedyoda/photo-stream:latest
       docker push ghcr.io/wickedyoda/photo-stream:latest